# prompts.toml

[prompt_with_last_code_and_errors]
template = """
You are given the last code attempt made to fix a bug, along with the resulting compiler error output.

Follow these steps:

1. Carefully read the previous Java code attempt below.
2. Analyze the compiler output to diagnose the cause of the compilation failure.
3. Determine whether the error relates to this specific hunk or another part of the multi-hunk context.
4. If this hunk is responsible, correct the code accordingly. If not, ensure this hunk is still correctly implemented and ready to integrate with other code fixes.
5. You may introduce necessary changes such as new imports, updated variable references, or method signatures—but **only if required** to resolve the compilation error.
6. Maintain the original Java formatting, naming conventions, and structure. Do not rewrite or reorder unrelated parts.
7. Your output must contain only the corrected Java code—**no comments, no explanations, no markdown, no triple backticks**.
8. You must **not change the Java version, formatting, or naming conventions**. This includes, but is not limited to:
   - Do NOT replace traditional for-loops with enhanced for-loops (e.g., `for (int i = 0; ... )` → `for (int x : list)`)
   - Do NOT use the diamond operator (`<>`) if the original code does not use it.
   - Do NOT change collections or APIs to use generics or streams if not originally used.
   - Do NOT replace `Hashtable`, `Vector`, `Enumeration`, or other legacy classes with modern equivalents.
   - Do NOT reformat, re-indent, or otherwise cosmetically alter unchanged code.
   - Do NOT change the use of anonymous classes to lambda expressions.
   - Do NOT import new classes, use new libraries, or alter package structures.  

Previous Code Attempt:
{{ last_code }}

Compilation Error Output:
{{ full_compiler_output }}

Please fix the bug in this code. Only return the corrected code. Do not provide comments, explanations, or any additional text. Return only the corrected code.
"""


[prompt_description_delineation_test_information_explicit_java]
template = """
{{ prompt_header }}

Bug Description:
{{ bug_description_title }}
{{ bug_description }}

Instructions:
1. Carefully read the Java code below. Buggy regions are explicitly marked between `<START_BUG>` and `<END_BUG>`.
2. Use the bug description to guide your understanding and correction.
3. Use the failing test cases and error messages to further diagnose the issue.
4. Based on this understanding, generate the corrected version of the code.
5. Your output must contain **only the corrected Java code**—no comments, explanations, or formatting wrappers like triple backticks.
6. Please only provide the code in Java. Every single bug will be in Java.
7. You must **not change the Java version, formatting, or naming conventions**. This includes, but is not limited to:
   - Do NOT replace traditional for-loops with enhanced for-loops (e.g., `for (int i = 0; ... )` → `for (int x : list)`)
   - Do NOT use the diamond operator (`<>`) if the original code does not use it.
   - Do NOT change collections or APIs to use generics or streams if not originally used.
   - Do NOT replace `Hashtable`, `Vector`, `Enumeration`, or other legacy classes with modern equivalents.
   - Do NOT reformat, re-indent, or otherwise cosmetically alter unchanged code.
   - Do NOT change the use of anonymous classes to lambda expressions.
   - Do NOT import new classes, use new libraries, or alter package structures.   
8. If `<START_BUG>` and `<END_BUG>` enclose nothing, this indicates an **insertion**; insert new code at that location.
9. Omit `<START_BUG>` and `<END_BUG>` markers from your output.
10. Provide the full corrected version of the entire file after applying your fix:
   - You **must return the full file**, not only the modified lines.
   - **Include all lines**, even those that were not changed, to ensure the file is contextually and syntactically complete.
   - The returned file must be a valid, self-contained Java file with no syntax errors.
   - Retain all unchanged code from the original file exactly as it was.

Buggy Java Code:
{{ delineated_bug }}

Test Failures:
{{ test_info_str }}

Return only the full corrected Java file code. Do not provide comments, explanations, or any additional text.
"""
